/**
 * @fileoverview gRPC-Web generated client stub for parkingSpace
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: parking-space.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as parking$space_pb from './parking-space_pb';


export class GetAvailableSpacesServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorgetAvailableSpaces = new grpcWeb.MethodDescriptor(
    '/parkingSpace.GetAvailableSpacesService/getAvailableSpaces',
    grpcWeb.MethodType.SERVER_STREAMING,
    parking$space_pb.Empty,
    parking$space_pb.ParkingSpaceList,
    (request: parking$space_pb.Empty) => {
      return request.serializeBinary();
    },
    parking$space_pb.ParkingSpaceList.deserializeBinary
  );

  getAvailableSpaces(
    request: parking$space_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<parking$space_pb.ParkingSpaceList> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/parkingSpace.GetAvailableSpacesService/getAvailableSpaces',
      request,
      metadata || {},
      this.methodDescriptorgetAvailableSpaces);
  }

}

